name: Kubernetes Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.17'
    - name: Install dependencies
      run: go get -d ./...
    - name: Run verify-all.sh
      run: hack/verify-all.sh
    - name: Run update-all.sh
      run: hack/update-all.sh
